### ISSUE TITLE
A problem occurred configuring project ':irondash_engine_context'

### ISSUE THREAD

**Issue by dLeff** [irondash/irondash#40]
Looks like a required ndkVersion is missing in a grade file:
```
* Where:
...../pub.dev/irondash_engine_context-0.4.0/cargokit/gradle/plugin.gradle' line: 140

* What went wrong:
A problem occurred configuring project ':irondash_engine_context'.
> Failed to notify project evaluation listener.
   > Please set 'android.ndkVersion' in 'app/build.gradle'.
   > Please set 'android.ndkVersion' in 'app/build.gradle'.
   > Please set 'android.ndkVersion' in 'app/build.gradle'.
```
Version 0.4.0

**Comment by knopp** [comment]
You need to set ndkVersion inside your root project `app/build.gradle`. It should be set to `flutter.ndkVersion` by default.

**Comment by m-j-g** [comment]
I'm getting the same error for this library and flutter.ndkVersion is set in the build.gradle.

**Comment by OpenJarvisAI** [comment]
How>?
irondash_engine_context-0.5.2/cargokit/gradle/plugin.gradle' line: 140

* What went wrong:
A problem occurred configuring project ':irondash_engine_context'.
> Failed to notify project evaluation listener.
   > Please set 'android.ndkVersion' in 'app/build.gradle'.

**Comment by OpenJarvisAI** [comment]
Can u just bother add some setup steps in README avoid so many new comers's issues?

**Comment by knopp** [comment]
android.sdkVersion is by default set for newly created Flutter project. And the error message clearly says what is missing. PR for improved documentation is always welcome.

**Comment by OpenJarvisAI** [comment]
it;s ndkVersion ...

**Comment by knopp** [comment]
I meant NDK version.

```
android {
    ...
    ndkVersion flutter.ndkVersion
```

This should be present by default in any Flutter generated project file.
